<a href="https://colab.research.google.com/github/leandrorodor/ALR-Machine_Learning_AS/blob/main/regressao_logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Entendendo os dados e o problema

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter

Download Dataset: [avaliacoes_usuario.csv](https://s3.amazonaws.com/caelum-online-public/machine-learning-aprendizado-supervisionado/avaliacoes_usuario.csv)

In [2]:
movies = pd.read_csv('/content/sample_data/avaliacoes_usuario.csv')

In [3]:
movies.head(5)

Titulo  Documentary  ...  Investimento  Gostou
0              Nixon (1995)            0  ...      7.930748       1
1  Leaving Las Vegas (1995)            0  ...     18.276555       1
2         Persuasion (1995)            0  ...     16.582232       1
3               Babe (1995)            0  ...     13.004553       1
4         Carrington (1995)            0  ...     14.418120       1

[5 rows x 17 columns]

In [4]:
Counter(movies['Gostou'])

Counter({0: 135, 1: 543})

In [12]:
print('Gostou {}'.format((543/(135+543))))

Gostou 0.8008849557522124


In [13]:
print('Não gostou {}'.format((135/(135+543))))

Não gostou 0.19911504424778761


In [14]:
cat = movies[movies.columns[1:16]]
likes = movies[movies.columns[16:]]

In [17]:
#treino, teste, treino_labels, teste_labels = train_test_split(cat, likes, test_size=0.1)
treino, teste, treino_labels, teste_labels = train_test_split(cat, likes)

In [20]:
type(treino),len(treino)

(pandas.core.frame.DataFrame, 508)

In [19]:
Counter(treino_labels['Gostou'])

Counter({0: 95, 1: 413})

In [ ]:
Counter(teste_labels['Gostou'])

Counter({0: 35, 1: 135})

In [23]:
print('Gostou % {} do treino_label (deve manter a proporção +- 80%)'.format(413/(95+413)))

Gostou % 0.812992125984252 do treino_label (deve manter a proporção +- 80%)


In [24]:
print('Gostou % {} do teste_label (deve manter a proporção +- 80%)'.format(135/(35+135)))

Gostou % 0.7941176470588235 do teste_label (deve manter a proporção +- 80%)


## Regressão logística

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.naive_bayes import MultinomialNB,GaussianNB

In [ ]:
type(treino)

pandas.core.frame.DataFrame

In [ ]:
treino[0:1]

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
344            0       0        0       1        0         0      0        0   

     Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
344       0          0         0      0          0  131.165837     39.479492

In [ ]:
treino = np.array(treino).reshape(len(treino), 15)
teste = np.array(teste).reshape(len(teste), 15)

In [ ]:
type(treino)

numpy.ndarray

In [ ]:
treino[0]

array([   0.        ,    0.        ,    0.        ,    1.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,  131.1658368 ,   39.47949166])

In [ ]:
type(treino_labels)

pandas.core.frame.DataFrame

In [ ]:
treino_labels.head(5)

Gostou
344       1
290       1
491       1
253       1
511       1

In [ ]:
treino_labels = treino_labels.values.ravel()
teste_labels = teste_labels.values.ravel()

In [ ]:
type(treino_labels)

numpy.ndarray

In [ ]:
treino_labels[0:5]

array([1, 1, 1, 1, 1])

In [ ]:
treino_labels.shape

(508,)

#### Usando regressão logistica

In [ ]:
modelo = LogisticRegression()
modelo.fit(treino, treino_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [ ]:
previsoes = modelo.predict(teste)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
teste_labels.shape

(170,)

In [ ]:
previsoes.shape

(170,)

In [ ]:
acuracia = accuracy_score(teste_labels, previsoes)
acuracia

0.79411764705882348

In [ ]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo.predict([zootopia])

array([1])

#### Usando Multinomial Naive Bayes

In [ ]:
modelo_NB = MultinomialNB()

In [ ]:
modelo_NB.fit(treino,treino_labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
previsoes_NB = modelo_NB.predict(teste)

In [ ]:
acuracia = accuracy_score(teste_labels, previsoes_NB)
acuracia

0.78235294117647058

In [ ]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_NB.predict([zootopia])

array([1])

#### EXTRA: Usando Gaussian Naive Bayes

In [ ]:
modelo_GNB = GaussianNB()

In [ ]:
modelo_GNB.fit(treino,treino_labels)

GaussianNB(priors=None)

In [ ]:
previsoes_GNB = modelo_GNB.predict(teste)

In [ ]:
acuracia = accuracy_score(teste_labels, previsoes_GNB)
acuracia

0.69411764705882351

In [ ]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_GNB.predict([zootopia])

array([1])