<a href="https://colab.research.google.com/github/leandrorodor/ALR-Machine_Learning_AS/blob/main/regressao_linear_multipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regressão linear múltipla

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

Download Dataset: [rlma.csv](https://s3.amazonaws.com/caelum-online-public/machine-learning-aprendizado-supervisionado/movies_multilinear_reg.csv)

In [3]:
movies = pd.read_csv('/content/sample_data/rlma.csv')

In [ ]:
type(movies)

pandas.core.frame.DataFrame

In [ ]:
movies.head(10)

movieId                              Titulo  Documentary  Sci-Fi  Mystery  \
0        1                    Toy Story (1995)            0       0        0   
1        2                      Jumanji (1995)            0       0        0   
2        3             Grumpier Old Men (1995)            0       0        0   
3        4            Waiting to Exhale (1995)            0       0        0   
4        5  Father of the Bride Part II (1995)            0       0        0   
5        6                         Heat (1995)            0       0        0   
6        7                      Sabrina (1995)            0       0        0   
7        8                 Tom and Huck (1995)            0       0        0   
8        9                 Sudden Death (1995)            0       0        0   
9       10                    GoldenEye (1995)            0       0        0   

   Horror  Romance  Thriller  Crime  Fantasy  Comedy  Animation  Children  \
0       0        0         0      0        1       1          1         1   
1       0        0         0      0        1       0          0         1   
2       0        1         0      0        0       1          0         0   
3       0        1         0      0        0       1          0         0   
4       0        0         0      0        0       1          0         0   
5       0        0         1      1        0       0          0         0   
6       0        1         0      0        0       1          0         0   
7       0        0         0      0        0       0          0         1   
8       0        0         0      0        0       0          0         0   
9       0        0         1      0        0       0          0         0   

   Drama  Adventure     Duracao  Investimento   Bilheteria  
0      0          1  103.468310     11.048216  5623234.602  
1      0          1  112.337916     14.927678  5714951.757  
2      0          0  116.245732     27.114597  9524339.124  
3      1          0  120.317732      4.994242  6331568.779  
4      0          0  110.023572     19.142246  6409617.277  
5      0          0   97.324845      9.977311  4956557.317  
6      0          0   88.978893     14.257461  4654565.066  
7      0          1   78.536011      8.871800  3950017.325  
8      0          0  104.934703     29.112800  6850971.551  
9      0          1  105.899475      3.695241  5157865.850

In [4]:
movies.shape

(9125, 18)

In [8]:
filmes_independente = movies[movies.columns[2:17]]

In [9]:
type(filmes_independente)

pandas.core.frame.DataFrame

In [10]:
filmes_dependente = movies[movies.columns[17:]]

In [11]:
filmes_dependente

Bilheteria
0     5.623235e+06
1     5.714952e+06
2     9.524339e+06
3     6.331569e+06
4     6.409617e+06
...            ...
9120  6.318999e+06
9121  5.300340e+06
9122  6.945211e+06
9123  6.459004e+06
9124  1.063624e+07

[9125 rows x 1 columns]

In [ ]:
type(filmes_dependente)

pandas.core.frame.DataFrame

In [ ]:
train, test, train_bilheteria, test_bilheteria = train_test_split(filmes_independente, filmes_dependente)

In [ ]:
train.head()

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
7505            0       0        0       0        0         0      1        0   
909             0       0        0       0        0         0      0        0   
8308            0       0        0       0        0         0      0        0   
416             0       0        0       0        1         0      0        0   
4728            0       0        0       0        0         0      0        0   

      Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
7505       1          0         0      0          0  111.247325     41.496397  
909        0          0         0      1          0  129.757430      3.751061  
8308       1          0         0      0          0  139.792106     32.107787  
416        1          0         0      0          0  120.752073      6.473384  
4728       0          0         0      0          0   96.975762      4.128282

In [ ]:
train.shape[0]

6843

In [ ]:
test.shape[0]

2282

In [ ]:
modelo = LinearRegression()
modelo.fit(train,train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

#### 1,Toy Story (1995),0,0,0,0,0,0,0,1,1,1,1,0,1,103.4683096,11.04821649,5623234.602

In [ ]:
modelo.predict([[0,0,0,0,0,0,0,1,1,1,1,0,1,103.4683096,11.04821649]])

array([[ 5828627.96965683]])

In [ ]:
modelo.score(train, train_bilheteria)

0.82728993267807627

In [ ]:
modelo.coef_

array([[ 42655.97503496,   6338.33598592, -13818.76605525, -23915.64582939,
         24775.47891531,  15437.82939179,  13901.13435994,  17001.12069112,
         -5758.97665963,  14581.77792254,  12879.50700613, -10960.33103084,
        -61189.27789748,  45674.3003098 ,  98955.21832726]])

In [ ]:
modelo.intercept_

array([ 31992.49848156])

In [ ]:
modelo.score(test, test_bilheteria)

0.82868767262936649

#### Zootopia
```
movieId,Titulo,Documentary,Sci-Fi,Mystery,Horror,Romance,Thriller,Crime,Fantasy,Comedy,Animation,Children,Drama,Adventure,Duracao,Investimento,Bilheteria
9999999,Zootopia,0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356,?????
```

In [ ]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo.predict([zootopia])

array([[ 7779149.0280967]])

### Split dos dados com test_size=0.3

In [ ]:
train, test, train_bilheteria, test_bilheteria = train_test_split(filmes_independente, filmes_dependente, test_size=0.3)

In [ ]:
modelo_30 = LinearRegression()
modelo_30.fit(train,train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [ ]:
modelo_30.score(test, test_bilheteria)

0.8324125338489522

In [ ]:
zootopia = [0,0,0,0,0,0,0,0,1,1,1,0,1,145.5170642,3.451632127]
modelo.predict([zootopia])

array([[ 6980452.63003705]])

In [ ]:
planeta_macaco = [0,1,0,0,0,0,0,0,0,0,0,0,0,150,5]
modelo.predict([planeta_macaco])

array([[ 7384251.97257379]])