<a href="https://colab.research.google.com/github/leandrorodor/ALR-Machine_Learning_AS/blob/main/regressao_logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Entendendo os dados e o problema

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter

Download Dataset: [avaliacoes_usuario.csv](https://s3.amazonaws.com/caelum-online-public/machine-learning-aprendizado-supervisionado/avaliacoes_usuario.csv)

In [2]:
movies = pd.read_csv('/content/sample_data/avaliacoes_usuario.csv')

In [3]:
movies.head(5)

Titulo  Documentary  ...  Investimento  Gostou
0              Nixon (1995)            0  ...      7.930748       1
1  Leaving Las Vegas (1995)            0  ...     18.276555       1
2         Persuasion (1995)            0  ...     16.582232       1
3               Babe (1995)            0  ...     13.004553       1
4         Carrington (1995)            0  ...     14.418120       1

[5 rows x 17 columns]

In [4]:
Counter(movies['Gostou'])

Counter({0: 135, 1: 543})

In [12]:
print('Gostou {}'.format((543/(135+543))))

Gostou 0.8008849557522124


In [13]:
print('Não gostou {}'.format((135/(135+543))))

Não gostou 0.19911504424778761


In [14]:
cat = movies[movies.columns[1:16]]
likes = movies[movies.columns[16:]]

In [17]:
#treino, teste, treino_labels, teste_labels = train_test_split(cat, likes, test_size=0.1)
treino, teste, treino_labels, teste_labels = train_test_split(cat, likes)

In [20]:
type(treino),len(treino)

(pandas.core.frame.DataFrame, 508)

In [19]:
Counter(treino_labels['Gostou'])

Counter({0: 95, 1: 413})

In [ ]:
Counter(teste_labels['Gostou'])

Counter({0: 35, 1: 135})

In [23]:
print('Gostou % {} do treino_label (deve manter a proporção +- 80%)'.format(413/(95+413)))

Gostou % 0.812992125984252 do treino_label (deve manter a proporção +- 80%)


In [24]:
print('Gostou % {} do teste_label (deve manter a proporção +- 80%)'.format(135/(35+135)))

Gostou % 0.7941176470588235 do teste_label (deve manter a proporção +- 80%)


## Regressão logística

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.naive_bayes import MultinomialNB,GaussianNB

In [26]:
type(treino),len(treino)

(pandas.core.frame.DataFrame, 508)

In [ ]:
treino[0:1]

Documentary  Sci-Fi  Mystery  Horror  Romance  Thriller  Crime  Fantasy  \
344            0       0        0       1        0         0      0        0   

     Comedy  Animation  Children  Drama  Adventure     Duracao  Investimento  
344       0          0         0      0          0  131.165837     39.479492

In [28]:
treino = np.array(treino).reshape(len(treino), 15)
teste = np.array(teste).reshape(len(teste), 15)

In [29]:
type(treino),len(treino)

(numpy.ndarray, 508)

In [30]:
treino.shape

(508, 15)

In [32]:
treino[0]

array([ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  1.        , 92.68674263,  4.87897061])

In [ ]:
type(treino_labels)

pandas.core.frame.DataFrame

In [ ]:
treino_labels.head(5)

Gostou
344       1
290       1
491       1
253       1
511       1

In [ ]:
treino_labels.values

In [35]:
treino_labels = treino_labels.values.ravel()
teste_labels = teste_labels.values.ravel()

In [45]:
type(treino_labels),len(treino_labels),treino_labels,treino_labels.shape,treino_labels[0:5]

(numpy.ndarray,
 508,
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1,

In [46]:
type(teste_labels),len(teste_labels),teste_labels,teste_labels.shape,teste_labels[0:5]

(numpy.ndarray,
 170,
 array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1]),
 (170,),
 array([1, 1, 1, 1, 0]))

In [60]:
modelo_1 = LogisticRegression(max_iter=150)

In [61]:
modelo_1.fit(treino,treino_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=150,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
previsoes_1 = modelo_1.predict(teste)
previsoes_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
acuracia_1 = accuracy_score(teste_labels, previsoes_1)
acuracia_1

0.7705882352941177

#### Usando Multinomial Naive Bayes

In [62]:
modelo_NB = MultinomialNB()

In [63]:
modelo_NB.fit(treino,treino_labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [64]:
previsoes_NB = modelo_NB.predict(teste)
previsoes_NB

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [65]:
acuracia = accuracy_score(teste_labels, previsoes_NB)
acuracia

0.7470588235294118

In [66]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_NB.predict([zootopia])

array([1])

#### EXTRA: Usando Gaussian Naive Bayes

In [67]:
modelo_GNB = GaussianNB()

In [68]:
modelo_GNB.fit(treino,treino_labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [69]:
previsoes_GNB = modelo_GNB.predict(teste)
previsoes_GNB

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1])

In [70]:
acuracia = accuracy_score(teste_labels, previsoes_GNB)
acuracia

0.6705882352941176

In [71]:
zootopia = [0,0,0,0,0,0,0,1,1,1,1,0,1,110,27.74456356]
modelo_GNB.predict([zootopia])

array([1])